import testServer from "../.jest/server"
import { remote } from "../src"

describe("#remote", () => {
  it("should only have the fields defined, nothing autogenerated", async () => {
    const res = await testServer({
      schemas: {
        graphql: remote("https://api.spacex.land/graphql")
      }
    }).then(({graphql}) => 
      graphql(`
      query {
        ships(limit: 1) {
          id
        }
      }
      `)
    ).then(res => res.data)

    console.log(JSON.stringify(res, null, 2))
    // instance.stop()
  })
})
